package HospitalModel;
import simView.*;
import genDevs.plots.*;
import java.awt.*;
import java.lang.*;
import genDevs.modeling.*;
import genDevs.simulation.*;
import GenCol.*;
import java.util.*;

public class Hospital extends ViewableDigraph {
	String IN = "IN", OUT = "OUT", outOne = "1OUT", outTwo = "2OUT", outThree = "3OUT";
	public Hospital() {
		super("Hospital");
		addInport(IN);
		addOutport(OUT);
		ViewableAtomic Patient = new Patient("Patient");
		add(Patient);
		ViewableAtomic EmergencyPatient = new Patient("EmergencyPatient");
		add(EmergencyPatient);
		ViewableAtomic Receptionist = new Receptionist("Receptionist");
		add(Receptionist);
		ViewableAtomic DoctorOne = new Doctor("DoctorOne");
		add(DoctorOne);
		ViewableAtomic DoctorTwo = new Doctor("DoctorTwo");
		add(DoctorTwo);
		ViewableAtomic DoctorThree = new Doctor("DoctorThree");
		add(DoctorThree);
		ViewableAtomic transducer = new Transducer("transducer");
		add(transducer);
		
		addCoupling(Patient, OUT, Receptionist, IN);
		addCoupling(EmergencyPatient, OUT, Receptionist, IN);
		addCoupling(Receptionist,outOne,DoctorOne,IN);
		addCoupling(Receptionist,outTwo,DoctorTwo,IN);
		addCoupling(Receptionist,outThree,DoctorThree,IN);
		addCoupling(DoctorOne,OUT,transducer,IN);
		addCoupling(DoctorTwo,OUT,transducer,IN);
		addCoupling(DoctorThree,OUT,transducer,IN);
		addCoupling(transducer, OUT, this, OUT);
		addCoupling(transducer, OUT, Receptionist, IN);
		
		
}
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(1031, 639);
        if((ViewableComponent)withName("DoctorOne")!=null)
             ((ViewableComponent)withName("DoctorOne")).setPreferredLocation(new Point(358, 49));
        if((ViewableComponent)withName("DoctorThree")!=null)
             ((ViewableComponent)withName("DoctorThree")).setPreferredLocation(new Point(395, 447));
        if((ViewableComponent)withName("EmergencyPatient")!=null)
             ((ViewableComponent)withName("EmergencyPatient")).setPreferredLocation(new Point(4, 400));
        if((ViewableComponent)withName("transducer")!=null)
             ((ViewableComponent)withName("transducer")).setPreferredLocation(new Point(623, 44));
        if((ViewableComponent)withName("DoctorTwo")!=null)
             ((ViewableComponent)withName("DoctorTwo")).setPreferredLocation(new Point(373, 230));
        if((ViewableComponent)withName("Patient")!=null)
             ((ViewableComponent)withName("Patient")).setPreferredLocation(new Point(-2, 64));
        if((ViewableComponent)withName("Receptionist")!=null)
             ((ViewableComponent)withName("Receptionist")).setPreferredLocation(new Point(152, 235));
    }
}
