package HospitalModel;
import simView.*;
import genDevs.plots.*;
import java.awt.*;
import java.lang.*;
import genDevs.modeling.*;
import genDevs.simulation.*;
import GenCol.*;
import java.util.*;

public class Hospital extends ViewableDigraph {
	String IN = "IN", OUT = "OUT";
	public Hospital() {
		super("Hospital");
		addInport(IN);
		addOutport(OUT);
		ViewableAtomic Patient = new Patient("Patient");
		add(Patient);
		ViewableAtomic EmergencyPatient = new Patient("EmergencyPatient");
		add(EmergencyPatient);
		ViewableAtomic Receptionist = new Receptionist("Receptionist");
		add(Receptionist);
		
		addCoupling(Patient, OUT, Receptionist, IN);
		addCoupling(EmergencyPatient, OUT, Receptionist, IN);
		addCoupling(Receptionist, OUT, this, OUT);
		
}
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(625, 341);
        if((ViewableComponent)withName("EmergencyPatient")!=null)
             ((ViewableComponent)withName("EmergencyPatient")).setPreferredLocation(new Point(72, 218));
        if((ViewableComponent)withName("Receptionist")!=null)
             ((ViewableComponent)withName("Receptionist")).setPreferredLocation(new Point(324, 140));
        if((ViewableComponent)withName("Patient")!=null)
             ((ViewableComponent)withName("Patient")).setPreferredLocation(new Point(79, 65));
    }
}
