name: Testing Actions

on:
  pull_request:
    branches:
      - master

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create PR
          uses: peter-evans/create-pull-request@v3
          with:
            title: added stuff
            reviewers: ${{ github.actor }}
            branch: adding stuff testing 1