name: Testing Actions

on:
  push:
    tags:
      - prod/*

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: checkout to branch
        uses: actions/checkout@v2
        
      - run: |
          version=0
          echo $version > ${{ github.workspace }}/Transducer2
          
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      - name: get the branch
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          branch="$(echo "${raw/origin\/}" | tr -d '[:space:]')"
          echo "currBranch=$branch" >> $GITHUB_ENV
          echo "$branch | tr -d ' '"
          echo "raw branch is $raw"
          echo "current branch is $branch"
          echo "length of branch is ${#branch}"

      - name: checkout to branch
        uses: actions/checkout@v2
        with:
          ref: ${{ env.currBranch }}

      - name: update file
        run: |
          version=0
          echo "current branch using env is ${{ env.currBranch }}"
          echo $version > ${{ github.workspace }}/Transducer

      - name: create PR
        uses: peter-evans/create-pull-request@v3
        with:
          title: added stuff
          reviewers: ${{ github.actor }}
          branch: adding-stuff-testing-${{ env.currBranch }}
          body: Automated PR to increase the patch number as a new prod tag has been pushed to ${{ env.currBranch }} branch.
          label: ${{ env.currBranch }}