name: Testing Actions

on:
  push:
    tags:
      - prod/*

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: checkout to branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      - name: get the branch
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          branch=${raw/origin\/}
          echo "currBranch=${branch}" >> $GITHUB_ENV
          echo "raw branch is $raw"
          echo "current branch is $branch"

      - name: checkout to branch
        uses: actions/checkout@v2
        with:
          ref: ${{ currBranch }}

      - name: update file
        run: |
          version=0
          echo $version > ${{ github.workspace }}/Transducer

      - name: create PR
        uses: peter-evans/create-pull-request@v3
        with:
          title: added stuff
          reviewers: ${{ github.actor }}
          branch: adding-stuff-testing-1
          # base: ${{ github.event.pull_request.base }}
          # base: master