name: Testing Actions

on:
  push:
    tags:
      - prod/*

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: get the branch
        run: |
          tag=${GITHUB_REF#refs/tags/}
          echo "tag is $tag"
      - name: checkout to branch
        uses: actions/checkout@v2
        with:
          ref: $branch
          # ref: ${{ github.event.pull_request.head.sha }}
          #ref: ${{ github.ref }}
      - name: update file
        run: |
          version=0
          echo $version > ${{ github.workspace }}/Transducer
      - name: create PR
        uses: peter-evans/create-pull-request@v3
        with:
          title: added stuff
          reviewers: ${{ github.actor }}
          branch: adding-stuff-testing-1
          # base: ${{ github.event.pull_request.base }}
          # base: master