name: Testing Actions

on:
  push:
    tags:
      - prod/*

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth:0
          # ref: ${{ github.event.pull_request.head.sha }}
          #ref: ${{ github.ref }}
      - name: update file
        run: |
          version=0
          echo $version > ${{ github.workspace }}/Transducer
          echo "branch name is ${{ github.ref }} OR ${ GITHUB_REF }"
          echo "edited branch name is ${GITHUB_REF##*/}"
      - name: create PR
        uses: peter-evans/create-pull-request@v3
        with:
          title: added stuff
          reviewers: ${{ github.actor }}
          branch: adding-stuff-testing-1
          # base: ${{ github.event.pull_request.base }}
          # base: master