name: Choco Package

on:
  workflow_dispatch: 

jobs:
  Testing:
    runs-on: windows-latest
    steps:
      - name: checkout to branch
        uses: actions/checkout@v2

      - name: Zipping the script
        run: | 
          Compress-Archive -Force -Path "{{ github.workspace }}/validationTool/scripts" -DestinationPath "./validationTool/testagain/package.zip"
          dir

      - name: checking
        run: |
          echo "hero"