name: Choco Package

on:
  workflow_dispatch: 

jobs:
  Testing:
    runs-on: windows-latest
    steps:
      - name: run only on testing-package
        if: github.ref != 'refs/heads/testing-package'
        run: |
          echo "Can only be run on testing-package"
          exit 1
    
      - name: checkout to branch
        uses: actions/checkout@v2

      - name: Zipping the script
        run: | 
          echo {{ github.ref }}
          Compress-Archive -Force -Path ".\validationTool\scripts" -DestinationPath ".\validationTool\testagain\tools\test.zip"
      
      - name: testing the zip package
        run: |
          Expand-Archive -Force -Path ".\validationTool\testagain\tools\test.zip" -DestinationPath ".\validationTool"
          dir ".\validationTool\testagain"

      - name: Chocolatey Package
        run: |
          $version = Get-Content -Path ".\validationTool\version_base"
          cd "validationTool\testagain"
          choco pack --version=$version
          dir
          cd ..\..

      - name: increment patch number
        run: |
          $version = Get-Content -Path ".\validationTool\version_base"
          dir
          $incVersion = .\scripts\increment.ps1 $version
          echo $incVersion
          git restore .
          git clean -f
          git status