name: Choco Package

on:
  workflow_dispatch: 

jobs:
  Testing:
    runs-on: windows-latest
    steps:
      - name: run only on testing-package
        if: github.ref != 'refs/heads/testing-package'
        run: |
          echo "this is a testing-package"
          exit 1
    
      - name: checkout to branch
        uses: actions/checkout@v2

      - name: Zipping the script
        run: | 
          Compress-Archive -Force -Path ".\validationTool\scripts" -DestinationPath ".\validationTool\testagain\tools\test.zip"

      - name: Chocolatey Package
        run: |
          $version = Get-Content -Path ".\validationTool\version_base"
          echo "action_state=yellow" >> $GITHUB_ENV
          cd "validationTool\testagain"
          cd ..\..

      - name: increment patch number
        run: |
          $version = Get-Content -Path ".\validationTool\version_base"
          $incVersion = .\scripts\increment.ps1 $version
          Set-Content -Path ".\validationTool\version_base" -Value $incVersion
          echo "${{ env.action_state }}"
          echo ${{ env.action_state }}

      - name: create PR
        uses: peter-evans/create-pull-request@v3
        with:
          title: Bump deployment tool patch version
          reviewers: ${{ github.actor }}
          branch: bump-deployment-tool-patch-version-develop
          body: Automated PR to increase the patch version of the deployment tool as a new choco package of tool has been pushed to jfrog.